### ISSUE TITLE
Possible bug 

### ISSUE THREAD

**Issue by IEncinas10** [ekiwi/fst-native#1]
Hello. First of all, thanks for the cool project(s).

Disclaimer: At this point I think **this isn't a bug on your project** but in some dependency, but as I'm a bit lost I'd like to know what your opinion is.

I tried using `surfer` to visualize some waves (which sadly I don't think I can share, but I could try to construct a shareable example) and got an error:

![313405935-bc69d39e-246a-4f38-bcec-3b8bc27533dd](https://github.com/ekiwi/fst-native/assets/42119338/03372543-bb8f-4d7b-bdde-a62825b7b5ed)

The error happens in latest version of the surfer project, and it also happens using https://github.com/ekiwi/wellen/blob/2e3bd5d08e4a89a8dbd5e2d6455577f20141cf85/examples/load_signals.rs. As I'm pretty lost trying to debug this what I did is:

1. Inspect the `value` string that triggers error. https://github.com/ekiwi/fst-native/blob/6ea031fba98f2a4705cbc3f0fa3aceed3203cc79/src/io.rs#L646
2. Inspect the same string as seen by `gtkwave` https://github.com/gtkwave/gtkwave/blob/f439c8ff0062d6125cb1c02b6f5bd19ebfae7453/lib/libfst/fstapi.c#L7134

The `value` string has a "cut" in the middle of the string, where the string from gtkwave matches the expected value. This makes your code error out because `parts.len() != 2 + element_count * 2`

My understanding is that those strings are compresed in the original file (it also looks like it after doing `hexdump -C waves.fst`. Therefore, my guess is that something went wrong when decompressing the string, which seems to be handled by `lz4_flex` from looking at the `Cargo.toml`.

Is there any information I can get from the `.fst` file like type of compression used for that string or something like it that might be helpful for debugging this issue?

**Comment by ekiwi** [comment]
Can you share the waveform file? Then I can run everything in a debugger in [RustRover](https://www.jetbrains.com/rust/).

**Comment by IEncinas10** [comment]
Sadly, I can't. Could you perhaps point me to where the files are decompressed or how I can extract information from the `fst` file (like the type of compression used for the string)? I saw in the `lz4_flex` that it doesn't support `LZ4HC`. Perhaps that could be the problem?

**Comment by ekiwi** [comment]
I don't remember the strings being compressed. Generally  I think that only the wave-data and not the meta-data is compressed. Can you share the exact string that you see in the Rust and in the C version?

**Comment by ekiwi** [comment]
The string is read here: https://github.com/ekiwi/fst-native/blob/6ea031fba98f2a4705cbc3f0fa3aceed3203cc79/src/io.rs#L811

There could be a bug in the [`read_c_str`](https://github.com/ekiwi/fst-native/blob/6ea031fba98f2a4705cbc3f0fa3aceed3203cc79/src/io.rs#L206) function. That would explain why the string is missing its suffix in my implementation.

**Comment by ekiwi** [comment]
Oh and the hierarchy _is_ compressed: 
- this function decompresses the hierarchy: https://github.com/ekiwi/fst-native/blob/6ea031fba98f2a4705cbc3f0fa3aceed3203cc79/src/io.rs#L570
- here you can see how we determine the compression type: https://github.com/ekiwi/fst-native/blob/6ea031fba98f2a4705cbc3f0fa3aceed3203cc79/src/reader.rs#L394

**Comment by ekiwi** [comment]
Would you be able to share the SystemVerilog definition of the enum that we are failing to parse? Also, can you confirm that your FST was generated with Verilator?

If you want to debug this library directly I would recommend making a test for your file here: https://github.com/ekiwi/fst-native/blob/6ea031fba98f2a4705cbc3f0fa3aceed3203cc79/tests/fst_reader_diff_tests.rs#L564

**Comment by IEncinas10** [comment]
Thank you very much for the pointers, and sorry again about not being able to share stuff. It is sad things work this way but I'm afraid I cant do much.

Indeed, the FST is generated with verilator, and looking at the file with `hexdump -C` I see a `7` before the string used to generate the enum table starts, so I guess that matches https://github.com/ekiwi/fst-native/blob/6ea031fba98f2a4705cbc3f0fa3aceed3203cc79/src/types.rs#L68

I'll try and compare how the string is decompressed in both codebases to see if I can spot the issue.

Thanks again!

**Comment by ekiwi** [comment]
> I'll try and compare how the string is decompressed in both codebases to see if I can spot the issue.

Can you share the concrete value of the string in the `fst-native` vs in the `GTKWave` code? While this might be a decompression issue, there is also a chance that our `read_c_str` function is wrong.


One other possible avenue to debug this would be to dump the result of `read_hierarchy_bytes`
 to disk and then run `hexdump -C` on that. That would allow you to distinguish between a decompression bug and a bug in reading the decompressed data.

**Comment by IEncinas10** [comment]
It looks like the string is decompressed correctly. I think I found the culprit:

https://github.com/ekiwi/fst-native/blob/6ea031fba98f2a4705cbc3f0fa3aceed3203cc79/src/types.rs#L12

The string is indeed larger than 512. This is 99% the issue. I'll try to figure out how to rebuild `wellen` with a modified version of `fst-native` that has a bigger constant for this thing 🤣

**Comment by ekiwi** [comment]
> The string is indeed larger than 512. This is 99% the issue. I'll try to figure out how to rebuild wellen with a modified version of fst-native that has a bigger constant for this thing

Oh, good find!

I think this might actually be a copy + paste error and we should be using `HIERARCHY_ATTRIBUTE_MAX_SIZE` in that context instead. I will try to push a fix either tonight or tomorrow.

**Comment by ekiwi** [comment]
Also, we should return an error instead of silently reading an unterminated string.

**Comment by IEncinas10** [comment]
Thats the issue. I just rebuilt `wellen` and could execute the `load_signal` example just fine, did the same with the whole `surfer` and now I can load the waves.

I had to go to `8192` because the string was larger than `2048` (a very large enum) 🤦🏻‍♂️. I guess you could go with a very big `max_len` because you won't use it unless you really need it, and if you go past that then just give an error.

**Comment by ekiwi** [comment]
Good job debugging and thank you very much for all your effort!

I will make sure to publish updates to `fst-native` and `wellen` tomorrow.

**Comment by IEncinas10** [comment]
No worries and thank you for being so helpful :)

**Comment by ekiwi** [comment]
Fixed in fst-native version 0.8.0. Thanks!

**Comment by ekiwi** [comment]
Surfer PR is out: https://gitlab.com/surfer-project/surfer/-/merge_requests/321
